### ISSUE TITLE
[Help Wanted] Can't compile application

### ISSUE THREAD

**Issue by Varun-Sethu** [MyNSB/Android#6]
I seem to be having an issue when compiling in Android Studio, there seems to be something wrong with the code in the 4u paper. It may be something wrong on my end, but could you take a look?

_Originally posted by @jono292 in https://github.com/MyNSB/Android/issues/5#issuecomment-466702036_

**Comment by Varun-Sethu** [comment]
@jono292 Could you please elaborate / describe where Android Studio says you are facing the issue?

**Comment by jono292** [comment]
There is an error when building with FourU.java, to do with "super(context, FourU.class);" I'm not the most experienced with Java, but it seems there's something wrong with the syntax. 

I fiddled around with the code to make it build, but when launching, it shows the splash screen, then eventually crashes (on both an Android Pie emulator and Android Oreo physical phone). Are you able to compile and run the app?

**Comment by Varun-Sethu** [comment]
There are errors with the current build on master and I am still yet to push out my changes, I recommend you revert to a previous commit in your local copy of the repo or alternatively you can use the pre-compiled APK in the release section. Otherwise I will alert you when I push the new updates.

**Comment by jono292** [comment]
Alright, got it. Installed the APK in releases, seems to be working great!
